system:
  mode: dev
  admin-email: admin@oicq.com
  admin-password: adminadmin
  http-port: 8899
  https-port: 443
  db-type: sqlite
mysql:
  address: 192.168.0.92
  port: 3306
  db-name: airgo-dev
  username: admin
  password: poiuty890
  config: charset=utf8mb4&parseTime=True&loc=Local
  max-idle-conns: 10
  max-open-conns: 100
sqlite:
  path: ./air.db